./general.sh msc25ahl &
./general.sh msc25apn & 
./general.sh msc25arg &
./general.sh msc25avj &
./general.sh msc25ccj &
./general.sh msc25cpd &
./general.sh msc25dcl &
./general.sh msc25dvh &
./general.sh msc25dvv &
./general.sh msc25icr &
./general.sh msc25jcs &
./general.sh msc25jzm &
./general.sh msc25leg &
./general.sh msc25maj &
./general.sh msc25mal &
./general.sh msc25mhr &            
./general.sh msc25ppa &
./general.sh msc25psg &
./general.sh msc25rrc &
./general.sh msc25sav &
./general.sh msc25ssc &
./general.sh msc25szg &
./general.sh msc25vhl &